New Tutorials Integration (#235)
* Added optional yarn cache to gitignore

* Remove preexisting hardhat/ directory

* Added Hardhat tutorials submodule

* Remove the preexisting truffle/ directory

* Added Truffle tutorials submodule

* Added Waffle tutorials submodule

* Renamed Hardhat tutorial projects so the naming won't clash with others

* Added submodules recursive checkout to CI

* Increased project folder max depth

* Added submodule recursive to all CI pipelines

* Aded alternative dependency versions for rush

* Fixed the naming of the rush projects for the CI

* Fixed tutorial/example references in bodhi.Dockerfile

* Add submodule initializtion to bodhi dockerfile

* Updated bodhi dockerfile to correctly reference the directories and commandas for tutorials

* Fix config for new examples (#200)

* added submodule

* use ubuntu-latest

* polish CI config

* use latest ref of submodule

* change config name to match new dockerfile

* update

* update examples

* update path for loop helper

* update hardhat version

* update loop

* update truffle examples

* update submodule

* update all submodules

* some clean up

* update hardhat submodule

* able to build

* add hardhat precompiled token rush config

* udpated docker CI config, waffle provider adapter tests passed

* update hardhat submodule

* polish

* add logs non zero check

* increase start delay time

* dump docker logs on failure

* roll back subql version

* polish

* disabled truffle failed tests

* update waffle tutorials

* update

* update

* add precompile token to docker

* skip waffle tutorials

* resolve lock

* fix lock and common version

Co-authored-by: Jan Turk <jan.turk12@gmail.com>

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -1,9 +1,12 @@
 name: E2E Tests
-on: push
+on:
+  push:
+    paths-ignore:
+      - '**/README.md'
 
 jobs:
   cancel-prev-runs:
-    runs-on: [self-hosted, linux]
+    runs-on: ubuntu-latest
     steps:
       - name: Cancel Previous Runs
         # Only cancel non-master branch runs
@@ -12,34 +15,14 @@ jobs:
         with:
           access_token: ${{ github.token }}
 
-  waffle-examples:
-    runs-on: [self-hosted, linux]
-    needs: cancel-prev-runs
-    steps:
-      - name: checkout
-        uses: actions/checkout@v2
-      - name: check docker info before cleaning
-        run: docker ps && docker volume ls
-      - name: clean up docker process and volumes
-        run: |
-          docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
-          docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
-          docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
-      - name: check docker info after cleaning
-        run: docker ps && docker volume ls
-      - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test --build -- waffle-examples-test
-
   eth-providers:
-    runs-on: [self-hosted, linux]
+    runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -55,13 +38,18 @@ jobs:
         run: docker ps && docker volume ls
       - name: test
         run: docker-compose up --abort-on-container-exit --exit-code-from=eth-providers-test --build -- eth-providers-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
 
   eth-rpc-adaptor:
-    runs-on: [self-hosted, linux]
+    runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -77,13 +65,18 @@ jobs:
         run: docker ps && docker volume ls
       - name: test
         run: docker-compose up --abort-on-container-exit --exit-code-from=eth-rpc-adapter-test --build -- eth-rpc-adapter-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
 
-  hardhat-examples:
-    runs-on: [self-hosted, linux]
+  waffle-examples:
+    runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -98,14 +91,46 @@ jobs:
       - name: check docker info after cleaning
         run: docker ps && docker volume ls
       - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-examples-test --build -- hardhat-examples-test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test --build -- waffle-examples-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
 
-  truffle-examples:
-    runs-on: [self-hosted, linux]
+  # waffle-tutorials:
+  #   runs-on: ubuntu-latest
+  #   needs: cancel-prev-runs
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         submodules: 'recursive'
+  #     - name: check docker info before cleaning
+  #       run: docker ps && docker volume ls
+  #     - name: clean up docker process and volumes
+  #       run: |
+  #         docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
+  #         docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
+  #     - name: check docker info after cleaning
+  #       run: docker ps && docker volume ls
+  #     - name: test
+  #       run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-tutorials-test --build -- waffle-tutorials-test
+  #     - name: dump docker logs on failure
+  #       if: failure()
+  #       uses: jwalton/gh-docker-logs@v1
+
+  hardhat-tutorials:
+    runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -120,4 +145,34 @@ jobs:
       - name: check docker info after cleaning
         run: docker ps && docker volume ls
       - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-examples-test --build -- truffle-examples-test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-tutorials-test --build -- hardhat-tutorials-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
+
+  truffle-tutorials:
+    runs-on: ubuntu-latest
+    needs: cancel-prev-runs
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      - name: check docker info before cleaning
+        run: docker ps && docker volume ls
+      - name: clean up docker process and volumes
+        run: |
+          docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
+          docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
+          docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
+      - name: check docker info after cleaning
+        run: docker ps && docker volume ls
+      - name: test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-tutorials-test --build -- truffle-tutorials-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
