CI v2 (#269)
* Added optional yarn cache to gitignore

* Remove preexisting hardhat/ directory

* Added Hardhat tutorials submodule

* Remove the preexisting truffle/ directory

* Added Truffle tutorials submodule

* Added Waffle tutorials submodule

* Renamed Hardhat tutorial projects so the naming won't clash with others

* Added submodules recursive checkout to CI

* Increased project folder max depth

* Added submodule recursive to all CI pipelines

* Aded alternative dependency versions for rush

* Fixed the naming of the rush projects for the CI

* Fixed tutorial/example references in bodhi.Dockerfile

* Add submodule initializtion to bodhi dockerfile

* Updated bodhi dockerfile to correctly reference the directories and commandas for tutorials

* Fix config for new examples (#200)

* added submodule

* use ubuntu-latest

* polish CI config

* use latest ref of submodule

* change config name to match new dockerfile

* update

* update examples

* update path for loop helper

* update hardhat version

* update loop

* update truffle examples

* update submodule

* update all submodules

* some clean up

* update hardhat submodule

* able to build

* add hardhat precompiled token rush config

* udpated docker CI config, waffle provider adapter tests passed

* update hardhat submodule

* polish

* add logs non zero check

* increase start delay time

* dump docker logs on failure

* roll back subql version

* polish

* disabled truffle failed tests

* update waffle tutorials

* update

* update

* add precompile token to docker

* skip waffle tutorials

* resolve lock

* fix lock and common version

* update hardhat tutorial

* hardhat tutorial integration

* can build with latest tutorials

* added new tutorial configs to docker

* test

* test

* test

* restart eth-rpc-adaptor if node is not ready

* refactor

* fix

* fix

* update hardhat examples

* fix bodhi version problem

* revert mandala version

* fix rpc adaptor setup

* delay eth provider tests start

* test

* test hardhat yarn

* test

* test dockerfile only hardhat

* separated docker files

* add tmate

* test

* clean up

* fix

* remove hardhat unit test

* combined e2e and unit tests

* clean up

* refactor docker compose file

* polish

* polish

Co-authored-by: Jan Turk <jan.turk12@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,8 @@
-name: E2E Tests
-on: push
+name: Tests
+on:
+  push:
+    paths-ignore:
+      - '**/README.md'
 
 jobs:
   cancel-prev-runs:
@@ -12,37 +15,16 @@ jobs:
         with:
           access_token: ${{ github.token }}
 
-  waffle-examples:
-    runs-on: ubuntu-latest
-    needs: cancel-prev-runs
-    steps:
-      - name: checkout
-        uses: actions/checkout@v2
-      - name: check docker info before cleaning
-        run: docker ps && docker volume ls
-      - name: clean up docker process and volumes
-        run: |
-          docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
-          docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
-          docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
-          docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
-      - name: check docker info after cleaning
-        run: docker ps && docker volume ls
-      - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test --build -- waffle-examples-test
-      - name: dump docker logs on failure
-        if: failure()
-        uses: jwalton/gh-docker-logs@v1
-
   eth-providers:
     runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -68,6 +50,10 @@ jobs:
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -87,12 +73,16 @@ jobs:
         if: failure()
         uses: jwalton/gh-docker-logs@v1
 
-  hardhat-examples:
+  waffle-examples:
     runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -107,17 +97,50 @@ jobs:
       - name: check docker info after cleaning
         run: docker ps && docker volume ls
       - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-examples-test --build -- hardhat-examples-test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-examples-test --build -- waffle-examples-test
       - name: dump docker logs on failure
         if: failure()
         uses: jwalton/gh-docker-logs@v1
 
-  truffle-examples:
+  # waffle-tutorials:
+  #   runs-on: ubuntu-latest
+  #   needs: cancel-prev-runs
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         submodules: 'recursive'
+  #     - name: Setup tmate session
+  #       uses: mxschmitt/action-tmate@v3
+  #     - name: check docker info before cleaning
+  #       run: docker ps && docker volume ls
+  #     - name: clean up docker process and volumes
+  #       run: |
+  #         docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
+  #         docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
+  #         docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
+  #     - name: check docker info after cleaning
+  #       run: docker ps && docker volume ls
+  #     - name: test
+  #       run: docker-compose up --abort-on-container-exit --exit-code-from=waffle-tutorials-test --build -- waffle-tutorials-test
+  #     - name: dump docker logs on failure
+  #       if: failure()
+  #       uses: jwalton/gh-docker-logs@v1
+
+  hardhat-tutorials:
     runs-on: ubuntu-latest
     needs: cancel-prev-runs
     steps:
       - name: checkout
         uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
       - name: check docker info before cleaning
         run: docker ps && docker volume ls
       - name: clean up docker process and volumes
@@ -132,7 +155,84 @@ jobs:
       - name: check docker info after cleaning
         run: docker ps && docker volume ls
       - name: test
-        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-examples-test --build -- truffle-examples-test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=hardhat-tutorials-test --build -- hardhat-tutorials-test
       - name: dump docker logs on failure
         if: failure()
         uses: jwalton/gh-docker-logs@v1
+
+  truffle-tutorials:
+    runs-on: ubuntu-latest
+    needs: cancel-prev-runs
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          submodules: 'recursive'
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
+      - name: check docker info before cleaning
+        run: docker ps && docker volume ls
+      - name: clean up docker process and volumes
+        run: |
+          docker rm -vf $(docker ps -a | grep bodhijs_subquery-node | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_graphql-engine | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_postgres | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_mandala-node | awk '{print $1}')  || true
+          docker rm -vf $(docker ps -a | grep bodhijs_eth-rpc-adapter-server | awk '{print $1}') || true 
+          docker rm -vf $(docker ps -a | grep bodhijs_loop | awk '{print $1}') || true
+          docker rm -vf $(docker ps -a | grep bodhijs_feed-tx | awk '{print $1}') || true
+      - name: check docker info after cleaning
+        run: docker ps && docker volume ls
+      - name: test
+        run: docker-compose up --abort-on-container-exit --exit-code-from=truffle-tutorials-test --build -- truffle-tutorials-test
+      - name: dump docker logs on failure
+        if: failure()
+        uses: jwalton/gh-docker-logs@v1
+
+  bodhi:
+    runs-on: ubuntu-latest
+    needs: cancel-prev-runs
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          submodules: recursive
+
+      - name: setup node env
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14.16.0'
+
+      - name: install dependencies
+        run: node common/scripts/install-run-rush.js update
+
+      - name: build
+        run: node common/scripts/install-run-rush.js build -t @acala-network/bodhi
+
+      - name: test
+        run: cd bodhi && yarn test
+        env:
+          NPM_TOKEN: doesnt-matter
+
+  eth-transactions:
+    runs-on: ubuntu-latest
+    needs: cancel-prev-runs
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+        with:
+          submodules: recursive
+
+      - name: setup node env
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14.16.0'
+
+      - name: install dependencies
+        run: node common/scripts/install-run-rush.js update
+
+      - name: build
+        run: node common/scripts/install-run-rush.js build -t @acala-network/eth-transactions
+
+      - name: test
+        run: cd eth-transactions && yarn test
